---
apiVersion: v1
kind: Pod
metadata:
  name: utils
  labels:
    app: utils
spec:
  containers:
  - name: utils
    image: ghcr.io/ministryofjustice/hmpps-delius-alfresco-utils:latest
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: "1"
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 512Mi
    securityContext:
      allowPrivilegeEscalation: false
      privileged: false
      readOnlyRootFilesystem: false
      runAsNonRoot: true
      runAsUser: 999
      capabilities:
        drop:
          - ALL
      seccompProfile:
        type: RuntimeDefault
    tty: true
    stdin: true
    command: ["/bin/bash"]
  serviceAccount: hmpps-migration-{{ $.Values.environment }}
  serviceAccountName: hmpps-migration-{{ $.Values.environment }}
  restartPolicy: Never
