apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: alfresco-content-services-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: alfresco-content-services-alfresco-repository
  minReplicas: 2
  maxReplicas: 8
  metrics:
  # Autoscale pods with a target of having 50% cpu usage.
  # In the event we've less than 50% overall it'll just scale down to
  # the minReplicas number of pods
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  behavior:
    scaleDown:
      policies:
      # Scale down pods no quicker than removing 1 pod per 5 minutes
      - type: Pods
        value: 1
        periodSeconds: 300
      stabilizationWindowSeconds: 300 # check every 5 minutess