apiVersion: apps/v1
kind: Deployment
metadata:
  name: alfresco-content-services-alfresco-search-enterprise-metadata
spec:
  template:
    spec:
      containers:
        - name: alfresco-search-enterprise-metadata
          env:
            - name: ALFRESCO_SHAREDFILESTORE_BASEURL
              value: https://alf-sfs.preprod.delius-core.hmpps-preproduction.modernisation-platform.service.justice.gov.uk/alfresco/api/-default-/private/sfs/versions/1/file/
