apiVersion: apps/v1
kind: Deployment
metadata:
  name: alfresco-content-services-libreoffice
spec:
  template:
    spec:
      containers:
        - name: alfresco-transform-service
          env:
            - name: FILE_STORE_URL
              value: https://alf-sfs.preprod.delius-core.hmpps-preproduction.modernisation-platform.service.justice.gov.uk/alfresco/api/-default-/private/sfs/versions/1/file
