apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: alfresco-search-enterprise-mediation
spec:
  serviceName: alfresco-search-enterprise-mediation
  selector:
    matchLabels:
      app: alfresco-search-enterprise-mediation
  template:
    spec:
      containers:
        - name: alfresco-search-enterprise-mediation
          env:
            - name: ALFRESCO_SHAREDFILESTORE_BASEURL
              value: https://alf-sfs.preprod.delius-core.hmpps-preproduction.modernisation-platform.service.justice.gov.uk/alfresco/api/-default-/private/sfs/versions/1/file/
