imagePullSecrets: quay-registry-secret
nameOverride: ""
fullnameOverride: ""
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
nodeSelector: {}
tolerations: []
affinity: {}
# -- Name of the existing search index, usually created by repo
indexName: alfresco
pathIndexingEnabled: true
postgresql:
  url: jdbc:postgresql://cloud-platform-f05612b0b7cdbf33.cdwm328dlye6.eu-west-2.rds.amazonaws.com:5432/alfresco
  hostname:
  database:
  existingSecretName: rds-instance-output
image:
  tag: 4.0.1
  repository: quay.io/alfresco/alfresco-elasticsearch-reindexing
resources:
  requests:
    cpu: "0.5"
    memory: "256Mi"
  limits:
    cpu: "2"
    memory: "2048Mi"
initcontainers:
  waitForRepository:
    resources:
      limits:
        cpu: "0.25"
        memory: "10Mi"
messageBroker:
  # --  Broker URL formatted as per:
  # https://activemq.apache.org/failover-transport-reference
  url: null
  # -- Broker username
  user: null
  # -- Broker password
  password: null
  # -- Provide connection details alternatively via an existing secret that contains BROKER_URL, BROKER_USERNAME and BROKER_PASSWORD keys
  existingSecretName: acs-alfresco-cs-brokersecret
global:
  alfrescoRegistryPullSecrets: quay-registry-secret
  # -- Shared connections details for Elasticsearch/Opensearch cluster
  elasticsearch:
    # -- The host where service is available
    host: opensearch-proxy-service-cloud-platform-62a206e0.hmpps-delius-alfrsco-poc.svc.cluster.local
    # -- The port where service is available
    port: 8080
    # -- Valid values are http or https
    protocol: http
    # -- The username required to access the service, if any
    user: null
    # -- The password required to access the service, if any
    password: null
    # -- Alternatively, provide connection details via an existing secret that contains ELASTICSEARCH_USERNAME and ELASTICSEARCH_PASSWORD keys
    existingSecretName:
