apiVersion: {{ template "common.capabilities.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ template "content-services.shortname" . }}-repository
  labels:
    {{- include "repository.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "alf_affinity_route"
    nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
    # Default file limit (1m) check, document(s) above this size will throw 413 (Request Entity Too Large) error
    nginx.ingress.kubernetes.io/proxy-body-size: {{ .Values.repository.ingress.maxUploadSize }}
    {{- include "ingress_annotations" .Values.repository }}
    {{- include "ingress_vhost_annotations" .Values.repository }}
    external-dns.alpha.kubernetes.io/aws-weight: "100"
    external-dns.alpha.kubernetes.io/set-identifier: "{{ template "content-services.shortname" . }}-repository-{{ .Release.Namespace }}-green"
spec:
  ingressClassName: default
  tls:
    - hosts:
        - {{ .Release.Namespace }}.{{ .Values.repository.ingress.hostName }}
  rules:
    - host: {{ .Release.Namespace }}.{{ .Values.repository.ingress.hostName }}
      http:
        paths:
          - path: {{ .Values.repository.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ template "content-services.shortname" . }}-repository
                port:
                  number: {{  .Values.repository.service.externalPort }}
          - path: {{ .Values.apiexplorer.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ template "content-services.shortname" . }}-repository
                port:
                  number: {{  .Values.repository.service.externalPort }}
