{{- $serviceName :=  printf "%s-%s" (include "content-services.shortname" .) "share" -}}
{{- $servicePort := .Values.share.service.externalPort -}}
apiVersion: {{ template "common.capabilities.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ template "content-services.shortname" . }}-share
  labels:
    {{- include "share.labels" . | nindent 4 }}
  annotations:
    # Default limit is 1m, document(s) above this size will throw 413 (Request Entity Too Large) error
    nginx.ingress.kubernetes.io/proxy-body-size: {{ .Values.repository.ingress.maxUploadSize }}
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "alfrescoShare"
    nginx.ingress.kubernetes.io/session-cookie-path: "/share"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "604800"
    nginx.ingress.kubernetes.io/session-cookie-expires: "604800"
    {{- include "ingress_annotations" .Values.share }}
    {{- if ne .Values.share.ingress.hostName .Values.repository.ingress.hostName }}
    {{- include "ingress_vhost_annotations" .Values.share }}
    {{- end }}
    external-dns.alpha.kubernetes.io/aws-weight: "100"
    external-dns.alpha.kubernetes.io/set-identifier: "{{ template "content-services.shortname" . }}-share-{{ .Release.Namespace }}-green"
spec:
  ingressClassName: default
  tls:
    - hosts:
        - {{ .Release.Namespace }}.{{ .Values.repository.ingress.hostName }}
  rules:
    - host: {{ .Release.Namespace }}.{{ .Values.repository.ingress.hostName }}
      http:
        paths:
          - path: {{ .Values.share.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ template "content-services.shortname" . }}-share
                port:
                  number: {{  .Values.share.service.externalPort }}
