# ACS Community values
repository:
  edition: Community
  replicaCount: 1
  image:
    repository: alfresco/alfresco-content-repository-community
    tag: 7.4.0.1
  persistence:
    accessModes:
      - ReadWriteOnce
pdfrenderer:
  replicaCount: 1
imagemagick:
  replicaCount: 1
libreoffice:
  replicaCount: 1
tika:
  replicaCount: 1
transformmisc:
  replicaCount: 1
share:
  replicaCount: 1
  image:
    repository: alfresco/alfresco-share
    tag: 7.4.0.1
alfresco-search:
  searchServicesImage:
    repository: alfresco/alfresco-search-services
    tag: "2.0.7"
  enabled: true
persistence:
  # -- If set to false data will be lost with pods
  enabled: true
  # -- Only define if you have a specific claim already created
  # existingClaim: "search-master-claim"
  VolumeSizeRequest: 10Gi
  search:
    data:
      mountPath: "/opt/alfresco-search-services/data"
      subPath: "alfresco-content-services/solr-data"
  EbsPvConfiguration:
    fsType: ext4
email:
  server:
    enabled: false
  inbound:
    enabled: false
imap:
  server:
    enabled: false
# Disable Enterprise only features
alfresco-search-enterprise:
  enabled: false
alfresco-digital-workspace:
  enabled: false
alfresco-sync-service:
  enabled: false
ai:
  enabled: false
s3connector:
  enabled: false
ooi:
  enabled: false
msTeams:
  enabled: false
