# this file overrides values defined in ./values.yaml
repository:
  replicaCount: 2
  resources:
    limits:
      cpu: 8
      memory: 32Gi
  persistence:
    baseSize: 100Gi
  environment: # override JAVA_OPTS to set XX:MaxRAM. TODO: this override can be removed once we can use cgroup v2 api
    JAVA_OPTS: >-
      -Dtransform.service.enabled=true
      -XX:MinRAMPercentage=50
      -XX:MaxRAMPercentage=80
      -XX:MaxRAM=32212254720
      -Dencryption.keystore.type=JCEKS
      -Dencryption.cipherAlgorithm=DESede/CBC/PKCS5Padding
      -Dencryption.keyAlgorithm=DESede
      -Dencryption.keystore.location=/usr/local/tomcat/shared/classes/alfresco/extension/keystore/keystore
      -Dmetadata-keystore.aliases=metadata
      -Dmetadata-keystore.metadata.algorithm=DESede
      -Dsystem.workflow.engine.activiti.enabled=false
      -Dsystem.prop_table_cleaner.algorithm=V2
      -Dsystem.delete_not_exists.read_only=false
      -Dsystem.delete_not_exists.timeout_seconds=3600
share:
  replicaCount: 1
alfresco-search:
  resources:
    limits:
      cpu: 8
      memory: 32Gi
  environment:
    SOLR_JAVA_MEM: >-
      -XX:MinRAMPercentage=50
      -XX:MaxRAMPercentage=80
      -XX:MaxRAM=32212254720
  persistence:
    VolumeSizeRequest: 2Ti
tika:
  replicaCount: 4 # use more replicas for initial indexing. TODO: reduce to 2 for normal operation
  resources:
    limits:
      cpu: 2
      memory: 4Gi
  environment:
    JAVA_OPTS: >-
      -Xms1024M
      -Xmx3276M
global:
  whitelistSourceRanges:
    - "3.10.104.193"       # legacy delius-stage-az1-nat-gateway
    - "3.11.26.150"        # legacy delius-stage-az2-nat-gateway
    - "18.130.189.137"     # legacy delius-stage-az3-nat-gateway
    - "35.178.209.113"     # Cloud Platform live-1-eu-west-2a
    - "3.8.51.207"         # Cloud Platform live-1-eu-west-2c
    - "35.177.252.54"      # Cloud Platform live-1-eu-west-2b
    - "35.176.93.186/32"   # MoJ GlobalProtect
    - "35.177.125.252/32"  # MoJ VPN Gateway Proxies
    - "35.177.137.160/32"  # MoJ VPN Gateway Proxies
    - "81.134.202.29/32"   # MoJ VPN
    - "51.149.250.0/24"    # PTTP / MoJO Production Account BYOIP CIDR range
    - "51.149.251.0/24"    # PTTP / MoJO Production Account BYOIP CIDR range - PreProd
    - "213.121.161.112/28" # 102 Petty France WiFi
    - "217.33.148.210/32"  # Digital studio
    - "13.43.9.198/32"     # MP non_live_data-public-eu-west-2a-nat
    - "13.42.163.245/32"   # MP non_live_data-public-eu-west-2b-nat
    - "18.132.208.127/32"  # MP non_live_data-public-eu-west-2c-nat
    - "51.149.249.0/29"    # ARK Corsham Internet Egress Exponential-E
    - "51.149.249.32/29"   # ARK Corsham Internet Egress Exponential-E
    - "194.33.192.0/25"    # ARK internet (DOM1)
    - "194.33.193.0/25"    # ARK internet (DOM1)
    - "194.33.196.0/25"    # ARK internet (DOM1)
    - "194.33.197.0/25"    # ARK internet (DOM1)
    - "195.59.75.0/24"     # ARK internet (DOM1)
    - "194.33.248.0/29"    # ARK Corsham Internet Egress Vodafone
    - "194.33.249.0/29"    # ARK Corsham Internet Egress Vodafone
    - "62.25.106.209/32"   # OMNI
    - "195.92.40.49/32"    # OMNI
    - "62.25.109.197/32"   # Quantum
    - "195.92.38.16/28"    # Quantum
    - "212.137.36.230/32"  # Quantum
    - "78.33.10.50/31"     # Unilink AOVPN
    - "78.33.10.52/30"     # Unilink AOVPN
    - "78.33.10.56/30"     # Unilink AOVPN
    - "78.33.10.60/32"     # Unilink AOVPN
    - "78.33.32.99/32"     # Unilink AOVPN
    - "78.33.32.100/30"    # Unilink AOVPN
    - "78.33.32.104/30"    # Unilink AOVPN
    - "78.33.32.108/32"    # Unilink AOVPN
    - "83.98.63.176/29"    # Unilink AOVPN
    - "194.75.210.216/29"  # Unilink AOVPN
    - "217.138.45.109/32"  # Unilink AOVPN
    - "217.138.45.110/32"  # Unilink AOVPN
