---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backup-pvc-script
data:
  entrypoint.sh: |-
    #!/bin/sh
    set -xe

    aws configure set default.s3.max_concurrent_requests 2000

    date=$(date +%Y%m%d%H%M%S)

    cd /pvc-mount/alfresco-content-services/solr-data

    tar -czf /tmp/solr-data-${date}.tar.gz alfresco alfrescoModels archive   

    aws s3 cp /tmp/solr-data-${date}.tar.gz s3://$DST_BUCKET/solr-data-${date}.tar.gz --no-progress --only-show-errors

    set +x
    echo backup of pvc mount directory completed

---
apiVersion: batch/v1
kind: Job
metadata:
  name: solr-backup-pvc
  labels:
    name-prefix: solr-backup-pvc
spec:
  template:
    spec:
      containers:
      - name: backup-pvc
        image: 754256621582.dkr.ecr.eu-west-2.amazonaws.com/webops/cloud-platform-service-pod:c5f69b4624b956248001fa7c173c89a0556a457e
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 4
            memory: 8Gi
        command:
        - /bin/entrypoint.sh
        env:
        - name: DST_BUCKET
          valueFrom:
            secretKeyRef:
              name: s3-backups-bucket-output
              key: BUCKET_NAME
        volumeMounts:
        - name: backup-pvc-script
          mountPath: /bin/entrypoint.sh
          readOnly: true
          subPath: entrypoint.sh
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 1001
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault
      serviceAccount: hmpps-migration-poc
      serviceAccountName: hmpps-migration-poc
      restartPolicy: OnFailure
      volumes:
      - name: backup-pvc-script
        configMap:
          name: backup-pvc-script
          defaultMode: 0755
      - name: pvc-mount
        persistentVolumeClaim:
          claimName: alfresco-content-services-alfresco-search-solr-claim
          
  backoffLimit: 10
