---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "alfresco-sync-service.fullname" . }}-configmap
  labels:
    {{- include "alfresco-sync-service.labels" . | nindent 4 }}
data:
  JAVA_OPTS: >-
      -Dsql.db.url=jdbc:postgresql://$RDS_INSTANCE_ENDPOINT/$DATABASE_NAME
      -Dsql.db.driver={{ include "alfresco-sync-service.dbDriver" . | quote }}
      -Dsql.db.username=$DATABASE_USERNAME
      -Dsql.db.password=$DATABASE_PASSWORD
      -Drepo.hostname={{ template "alfresco-sync-service.repository" . }}
      -Drepo.port={{ .Values.repository.port }}
      -Ddw.server.applicationConnectors[0].type=http
      -Dmessaging.broker.url=$BROKER_URL
      -Dmessaging.username=$BROKER_USERNAME
      -Dmessaging.password=$BROKER_PASSWORD
      {{ .Values.environment.JAVA_OPTS }}
      {{ .Values.environment.EXTRA_JAVA_OPTS }}
