apiVersion: v1
kind: ConfigMap
metadata:
  name: empty-s3-script
  labels:
    action: empty-s3-bucket
data:
  delete-s3.sh: |-
    #!/bin/sh
    set -euo pipefail

    BUCKET="${BUCKET}"
    REGION="${AWS_REGION}"

    echo "Bucket: ${BUCKET}"
    echo "Region: ${REGION}"

    # Delete current object versions
    SHARD_INDEX=${JOB_COMPLETION_INDEX}
    echo "Starting shard $SHARD_INDEX of $TOTAL_SHARDS for bucket $BUCKET"
    NEXT_TOKEN=""

    while true; do
      versions=$(aws s3api list-object-versions --bucket "$BUCKET" \
                  --max-items 1000 \
                  --query "[Versions[].{Key: Key, VersionId: VersionId}, DeleteMarkers[].{Key: Key, VersionId: VersionId}]" \
                  --output text)

      if [ -z "$versions" ]; then
        echo "No more versions left for shard $SHARD_INDEX."
        break
      fi

      echo "$versions" | nl -ba | while read -r lineno key version; do
        shard=$(( (lineno - 1) % TOTAL_SHARDS ))
        if [ "$shard" -eq "$SHARD_INDEX" ]; then
          echo "[$SHARD_INDEX] Deleting $key (version $version)"
          aws s3api delete-object --bucket "$BUCKET" --key "$key" --version-id "$version"
        fi
      done
    done

    echo "s3 bucket emptying process....Done."