apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.release_name }}-configmap"
data:
  ELASTICSEARCH_INDEXNAME: "{{ .Values.indexName }}"
  {{ template "alfresco-search-enterprise.config.spring" . }}
  ALFRESCO_SHAREDFILESTORE_BASEURL: http://alfresco-content-services-alfresco-filestore:80/alfresco/api/-default-/private/sfs/versions/1/file/
  ALFRESCO_ACCEPTEDCONTENTMEDIATYPESCACHE_BASEURL: http://alfresco-content-services-alfresco-router/transform/config
  ALFRESCO_REINDEX_PATHINDEXINGENABLED: {{ .Values.pathIndexingEnabled | quote }}
  SPRING_DATASOURCE_URL: {{ .Values.postgresql.url }}
  {{- if .Values.environment }}
  {{- range $key, $val := .Values.environment }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- end }}
