---
apiVersion: v1
kind: ConfigMap
metadata:
  name: refresh-db-script
data:
  entrypoint.sh: |-
    #!/bin/bash
    set -e
    echo "${SRC_DB_HOST}:5432:${SRC_DB_NAME}:${SRC_DB_USER}:${SRC_DB_PASS}" > ~/.pgpass
    echo "${DST_DB_HOST}:5432:${DST_DB_NAME}:${DST_DB_USER}:${DST_DB_PASS}" >> ~/.pgpass
    chmod 0600 ~/.pgpass
    set -x

    pg_dump --host="$SRC_DB_HOST" --username="$SRC_DB_USER" --format=custom --no-owner --no-privileges --verbose --file=/tmp/db.dump $SRC_DB_NAME
    pg_restore --host="$DST_DB_HOST" --username="$DST_DB_USER" --clean --no-owner --verbose --dbname="$DST_DB_NAME" /tmp/db.dump
    rm -v /tmp/db.dump ~/.pgpass
---
apiVersion: batch/v1
kind: Job
metadata:
  name: refresh-db
spec:
  template:
    spec:
      containers:
      - name: refresh-db
        image: postgres:14
        imagePullPolicy: IfNotPresent
        command:
        - /bin/entrypoint.sh
        env:
        - name: SRC_DB_NAME
          valueFrom:
            secretKeyRef:
              name: rds-instance-output
              key: DATABASE_NAME
        - name: SRC_DB_USER
          valueFrom:
            secretKeyRef:
              name: rds-instance-output
              key: DATABASE_USERNAME
        - name: SRC_DB_PASS
          valueFrom:
            secretKeyRef:
              name: rds-instance-output
              key: DATABASE_PASSWORD
        - name: SRC_DB_HOST
          valueFrom:
            secretKeyRef:
              name: rds-instance-output
              key: RDS_INSTANCE_ADDRESS
        - name: DST_DB_NAME
          valueFrom:
            secretKeyRef:
              name: rds-instance-output-poc
              key: DATABASE_NAME
        - name: DST_DB_USER
          valueFrom:
            secretKeyRef:
              name: rds-instance-output-poc
              key: DATABASE_USERNAME
        - name: DST_DB_PASS
          valueFrom:
            secretKeyRef:
              name: rds-instance-output-poc
              key: DATABASE_PASSWORD
        - name: DST_DB_HOST
          valueFrom:
            secretKeyRef:
              name: rds-instance-output-poc
              key: RDS_INSTANCE_ADDRESS
        volumeMounts:
        - name: refresh-db-script
          mountPath: /bin/entrypoint.sh
          readOnly: true
          subPath: entrypoint.sh
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsUser: 999
      serviceAccount: hmpps-migration-development
      serviceAccountName: hmpps-migration-development
      restartPolicy: Never
      volumes:
      - name: refresh-db-script
        configMap:
          name: refresh-db-script
          defaultMode: 0755
  backoffLimit: 0
...
