---
apiVersion: v1
kind: ConfigMap
metadata:
  name: refresh-s3-script
data:
  entrypoint.sh: |-
    #!/bin/sh
    set -xe

    aws configure set default.s3.max_concurrent_requests 2000

    aws s3 sync s3://$SRC_BUCKET/ s3://$DST_BUCKET/ --delete
---
apiVersion: batch/v1
kind: Job
metadata:
  name: refresh-s3
spec:
  template:
    spec:
      containers:
      - name: refresh-s3
        image: 754256621582.dkr.ecr.eu-west-2.amazonaws.com/webops/cloud-platform-service-pod:c5f69b4624b956248001fa7c173c89a0556a457e
        imagePullPolicy: IfNotPresent
        command:
        - /bin/entrypoint.sh
        env:
        - name: SRC_BUCKET
          valueFrom:
            secretKeyRef:
              name: s3-bucket-output
              key: BUCKET_NAME
        - name: DST_BUCKET
          valueFrom:
            secretKeyRef:
              name: s3-bucket-output-poc
              key: BUCKET_NAME
        volumeMounts:
        - name: refresh-s3-script
          mountPath: /bin/entrypoint.sh
          readOnly: true
          subPath: entrypoint.sh
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 1001
      serviceAccount: hmpps-migration-development
      serviceAccountName: hmpps-migration-development
      restartPolicy: Never
      volumes:
      - name: refresh-s3-script
        configMap:
          name: refresh-s3-script
          defaultMode: 0755
  backoffLimit: 0
...
