apiVersion: v1
kind: ConfigMap
metadata:
  name: reindexing-{{ .Values.fromTime }}-{{ .Values.toTime }}-configmap
data:
  ELASTICSEARCH_INDEXNAME: "{{ .Values.indexName }}"
  {{ template "alfresco-search-enterprise.config.spring" . }}
  ALFRESCO_SHAREDFILESTORE_BASEURL: {{ (lookup "v1" "ConfigMap" .Release.Namespace .Values.sharedFileStore.sourceConfigMap).data.SFS_URL_API }}
  ALFRESCO_ACCEPTEDCONTENTMEDIATYPESCACHE_BASEURL: http://alfresco-content-services-transform-router/transform/config
  ALFRESCO_REINDEX_PATHINDEXINGENABLED: {{ .Values.pathIndexingEnabled | quote }}
  SPRING_DATASOURCE_URL: {{ .Values.postgresql.url }}
  {{- if .Values.environment }}
  {{- range $key, $val := .Values.environment }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- end }}
