apiVersion: v1
kind: ConfigMap
metadata:
  name: reindexing-{{ .Values.fromTime }}-{{ .Values.toTime }}-configmap
data:
  ELASTICSEARCH_INDEXNAME: "{{ .Values.indexName }}"
  {{ template "alfresco-search-enterprise.config.spring" . }}
  ALFRESCO_SHAREDFILESTORE_BASEURL: https://alf-sfs.preprod.delius-core.hmpps-preproduction.modernisation-platform.service.justice.gov.uk/alfresco/api/-default-/private/sfs/versions/1/file/
  ALFRESCO_ACCEPTEDCONTENTMEDIATYPESCACHE_BASEURL: http://alfresco-content-services-transform-router/transform/config
  ALFRESCO_REINDEX_PATHINDEXINGENABLED: {{ .Values.pathIndexingEnabled | quote }}
  SPRING_DATASOURCE_URL: {{ .Values.postgresql.url }}
  {{- if .Values.environment }}
  {{- range $key, $val := .Values.environment }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- end }}
