# this file overrides values defined in ./values.yaml
repository:
  replicaCount: 2
share:
  replicaCount: 1
externalHost: hmpps-delius-alfresco-dev.apps.live.cloud-platform.service.justice.gov.uk
externalProtocol: https
externalPort: 443
