# this file overrides values defined in ./values.yaml
alfresco-repository:
  replicaCount: 2
  image:
    repository: 754256621582.dkr.ecr.eu-west-2.amazonaws.com/hmpps-migration/alfresco-content-repository
    tag: release_7.3.2_elasticsearch-r5.0.4-content-latest
  persistence:
    # -- Persist repository data
    enabled: false
    baseSize: 100Gi
    # -- Specify a storageClass for dynamic provisioning
    accessModes:
      - ReadWriteOnce
share:
  replicaCount: 1
  image:
    repository: 754256621582.dkr.ecr.eu-west-2.amazonaws.com/hmpps-migration/alfresco-share
    tag: release_7.3.2_elasticsearch-r5.0.4-share-latest
externalPort: 443
global:
  known_urls:
    - https://hmpps-delius-alfresco-dev.apps.live.cloud-platform.service.justice.gov.uk
    - https://share.hmpps-delius-alfresco-dev.apps.live.cloud-platform.service.justice.gov.uk
    - https://alf-sfs.dev.delius-core.hmpps-development.modernisation-platform.service.justice.gov.uk
