# this file overrides values defined in ./values.yaml
repository:
  replicaCount: 1
  image:
    tag: release_7.3.2_elasticsearch-r5.0.2-content-latest
share:
  replicaCount: 1
  image:
    tag: release_7.3.2_elasticsearch-r5.0.2-share-latest
externalHost: hmpps-delius-alfrsco-poc.apps.live.cloud-platform.service.justice.gov.uk
externalProtocol: https
externalPort: 443
