# this file overrides values defined in ./values.yaml
repository:
  replicaCount: 1
share:
  replicaCount: 1
externalHost: hmpps-delius-alfrsco-poc.apps.live.cloud-platform.service.justice.gov.uk
externalProtocol: https
externalPort: 443
