# this file overrides values defined in ./values.yaml
alfresco-repository:
  environment:
  # We need s3.flatRoot=false to build the correct S3 folder structures with dates, 
  # however this property is deprecated and may be removed in future versions.
  # The com.sun.management.jmxremote settings are required for JMX monitoring.
    JAVA_OPTS: >-
      -Dindex.subsystem.name=elasticsearch
      -Delasticsearch.indexName=alfresco
      -Delasticsearch.createIndexIfNotExists=true
      -Dtransform.service.enabled=true
      -Dtransform.service.url=http://alfresco-content-services-transform-router
      -XX:MinRAMPercentage=50
      -XX:MaxRAMPercentage=80
      -Dencryption.keystore.type=JCEKS
      -Dencryption.cipherAlgorithm=DESede/CBC/PKCS5Padding
      -Dencryption.keyAlgorithm=DESede
      -Dencryption.keystore.location=/usr/local/tomcat/shared/classes/alfresco/extension/keystore/keystore
      -Dmetadata-keystore.aliases=metadata
      -Dmetadata-keystore.metadata.algorithm=DESede
      -Dsystem.workflow.engine.activiti.enabled=false
      -Dsystem.prop_table_cleaner.algorithm=V2
      -Dsystem.delete_not_exists.read_only=false
      -Dsystem.delete_not_exists.timeout_seconds=3600
      -Dfilecontentstore.subsystem.name=S3
      -Ds3.flatRoot=false
      -Dsfs.url=${SFS_URL}
      -Dcom.sun.management.jmxremote
      -Dcom.sun.management.jmxremote.port=9010
      -Dcom.sun.management.jmxremote.rmi.port=9010
      -Dcom.sun.management.jmxremote.local.only=false
      -Dcom.sun.management.jmxremote.authenticate=false
      -Dcom.sun.management.jmxremote.ssl=false
      -Djava.rmi.server.hostname=127.0.0.1
    CATALINA_OPTS: >-
      -Ds3.bucketLocation=eu-west-2
  replicaCount: 2
  image:
    repository: 754256621582.dkr.ecr.eu-west-2.amazonaws.com/hmpps-migration/alfresco-content-repository
    tag: release_7.3.2_elasticsearch-r5.0.4-content-latest
  persistence:
    # -- Persist repository data
    enabled: false
    baseSize: 100Gi
    # -- Specify a storageClass for dynamic provisioning
    accessModes:
      - ReadWriteOnce
share:
  replicaCount: 1
  image:
    repository: 754256621582.dkr.ecr.eu-west-2.amazonaws.com/hmpps-migration/alfresco-share
    tag: release_7.3.2_elasticsearch-r5.0.2-chart-7.0.3-share-latest
externalProtocol: https
externalPort: 443
alfresco-search-enterprise:
  liveIndexing:
  # set in value-versions yaml
    content:
      replicaCount: 1
    metadata:
      replicaCount: 1
    mediation:
      podSecurityContext:
        seccompProfile:
          type: RuntimeDefault
      replicaCount: 1
alfresco-transform-service:
  tika:
    podSecurityContext:
      seccompProfile:
        type: RuntimeDefault  
    replicaCount: 1
    resources:
      requests:
        cpu: "0.5"
        memory: "2048Mi"
      limits:
        cpu: "2"
        memory: 6Gi
  transformrouter:
    podSecurityContext:
      seccompProfile:
        type: RuntimeDefault  
    replicaCount: 1
    resources:
      requests:
        cpu: "0.75"
        memory: "512Mi"
      limits:
        cpu: "2"
        memory: 2Gi
  filestore:
    # -- Declares the alfresco-shared-file-store used by the content repository
    # and transform service
    enabled: false
    replicaCount: 1
    persistence:
      # -- Persist filestore data
      enabled: true
      data:
        mountPath: "/tmp/Alfresco"
        subPath: "alfresco-content-services/filestore-data"
    strategy:
      # -- Strategy must be set to Recreate when persistence supports only
      # `ReadWriteOnce` access mode. If `ReadWriteMany` is supported, then it
      # can be set to RollingUpdate.
      type: Recreate
    readinessProbe:
      httpGet:
        port: 80
    livenessProbe:
      httpGet:
        port: 80
    ports:
      - containerPort: 80
global:
  known_urls:
    - https://hmpps-delius-alfrsco-poc.apps.live.cloud-platform.service.justice.gov.uk
    - https://share.hmpps-delius-alfrsco-poc.apps.live.cloud-platform.service.justice.gov.uk
    - https://alf-sfs.poc.delius-core.hmpps-development.modernisation-platform.service.justice.gov.uk
