FROM quay.io/alfresco/alfresco-share:7.3.1

ARG TOMCAT_DIR=/usr/local/tomcat

USER root

 # Restore permissions
RUN chgrp -R nobody ${TOMCAT_DIR}/webapps && \
     find ${TOMCAT_DIR}/webapps -type d -exec chmod 0777 {} \; && \
     find ${TOMCAT_DIR}/webapps -type f -exec chmod 0777 {} \; && \
     find ${TOMCAT_DIR}/shared -type d -exec chmod 0777 {} \; && \
     find ${TOMCAT_DIR}/shared -type f -exec chmod 0777 {} \; && \
     chmod -R g+r ${TOMCAT_DIR}/webapps && \
     chgrp -R nobody ${TOMCAT_DIR}

 USER nobody