---
apiVersion: v1
kind: ConfigMap
metadata:
  name: migrate-db-script
data:
  entrypoint.sh: |-
    #!/bin/bash
    set -e
    trap 'send_slack_notification $?' EXIT

    function send_slack_notification() {
      STATUS=$1
      if [ "$STATUS" -eq 0 ]; then
        JSON_PAYLOAD=$(jq -n --arg text "Alfresco Migrate DB (${DST_ENV}) job succeeded" '{text: $text}')
      else
        JSON_PAYLOAD=$(jq -n --arg text "Alfresco Migrate DB (${DST_ENV}) job failed" '{text: $text}')
      fi
      if [ -n "$SLACK_WEBHOOK_URL" ]; then
        curl -X POST -H 'Content-type: application/json' --data "$JSON_PAYLOAD" $SLACK_WEBHOOK_URL
      else
        echo "SLACK_WEBHOOK_URL is not set, cannot send notification: ${JSON_PAYLOAD}"
      fi
    }

    echo "${SRC_DB_HOST}:5432:${SRC_DB_NAME}:${SRC_DB_USER}:${SRC_DB_PASS}" > ~/.pgpass
    echo "${DST_DB_HOST}:5432:${DST_DB_NAME}:${DST_DB_USER}:${DST_DB_PASS}" >> ~/.pgpass
    chmod 0600 ~/.pgpass
    chown job:job ~/.pgpass
    set -x

    # Dump the source database
    pg_dump --jobs=8 --host="$SRC_DB_HOST" --username="$SRC_DB_USER" --dbname="$SRC_DB_NAME" --no-owner --no-privileges --verbose --format=directory --file=/home/job/db-dump

    psql --host="$DST_DB_HOST" --username="$DST_DB_USER" --dbname="$DST_DB_NAME" -c "drop schema if exists public cascade;"

    psql --host="$DST_DB_HOST" --username="$DST_DB_USER" --dbname="$DST_DB_NAME" -c "create schema public;"

    # Restore the source database dump to the destination database
    pg_restore --jobs=6 --host="$DST_DB_HOST" --username="$DST_DB_USER" --dbname="$DST_DB_NAME" --no-owner --no-privileges --verbose /home/job/db-dump

    if [ -n "$SLACK_WEBHOOK_URL" ]; then
      JSON_PAYLOAD=$(jq -n --arg text "Alfresco Migrate DB (${DST_ENV}) completed. Starting post-migration steps" '{text: $text}')
      curl -X POST -H 'Content-type: application/json' --data "$JSON_PAYLOAD" $SLACK_WEBHOOK_URL
    fi

    echo "Write the following SQL statements to a file in /tmp and execute them"
    cat > /tmp/alf-patches.sql <<'EOF'
      \timing

      -- patch.db-V4.2-metadata-query-indexes
      -- These indexes should already exist if the DB is at version 6.0 or higher but as the script 
      -- is marked as having been skipped we need to ensure they are created.
      CREATE INDEX idx_alf_node_mdq ON alf_node (store_id, type_qname_id, id);
      CREATE INDEX idx_alf_node_cor ON alf_node (audit_creator, store_id, type_qname_id, id);
      CREATE INDEX idx_alf_node_crd ON alf_node (audit_created, store_id, type_qname_id, id);
      CREATE INDEX idx_alf_node_mor ON alf_node (audit_modifier, store_id, type_qname_id, id);
      CREATE INDEX idx_alf_node_mod ON alf_node (audit_modified, store_id, type_qname_id, id);
      CREATE INDEX idx_alf_nprop_s ON alf_node_properties (qname_id, string_value, node_id);
      CREATE INDEX idx_alf_nprop_l ON alf_node_properties (qname_id, long_value, node_id);
      CREATE INDEX idx_alf_conturl_sz ON alf_content_url (content_size, id);

      --
      -- Record script finish
      --
      INSERT INTO alf_applied_patch
        (id, description, fixes_from_schema, fixes_to_schema, applied_to_schema, target_schema, applied_on_date, applied_to_server, was_executed, succeeded, report)
        VALUES
        (
          'patch.db-V4.2-metadata-query-indexes', 'Manually executed script upgrade V4.2: Updates for metadata query',
          0, 6023, -1, 6024, now(), 'UNKNOWN', TRUE, TRUE, 'Script completed'
        );
      COMMIT;

      -- patch.db-V5.1-metadata-query-indexes
      CREATE INDEX idx_alf_nprop_b ON alf_node_properties (qname_id, boolean_value, node_id);
      CREATE INDEX idx_alf_nprop_f ON alf_node_properties (qname_id, float_value, node_id);
      CREATE INDEX idx_alf_nprop_d ON alf_node_properties (qname_id, double_value, node_id);

      INSERT INTO alf_applied_patch
        (id, description, fixes_from_schema, fixes_to_schema, applied_to_schema, target_schema, applied_on_date, applied_to_server, was_executed, succeeded, report)
        VALUES
        (
          'patch.db-V5.1-metadata-query-indexes', 'Manually executed script upgrade V5.1: Updates for metadata query',
          0, 9003, -1, 9004, now(), 'UNKNOWN', TRUE, TRUE, 'Script completed'
        );
      COMMIT;

      -- patch.db-V5.2-remove-jbpm-tables-from-db
      ALTER TABLE JBPM_ACTION DROP CONSTRAINT fk_action_actndel; -- (optional)
      ALTER TABLE JBPM_ACTION DROP CONSTRAINT FK_ACTION_EVENT; -- (optional)
      ALTER TABLE JBPM_ACTION DROP CONSTRAINT FK_ACTION_EXPTHDL; -- (optional)
      ALTER TABLE JBPM_ACTION DROP CONSTRAINT FK_ACTION_PROCDEF; -- (optional)
      ALTER TABLE JBPM_ACTION DROP CONSTRAINT FK_ACTION_REFACT; -- (optional)
      ALTER TABLE JBPM_ACTION DROP CONSTRAINT fk_crtetimeract_ta; -- (optional)
      ALTER TABLE JBPM_BYTEARRAY DROP CONSTRAINT FK_BYTEARR_FILDEF; -- (optional)
      ALTER TABLE JBPM_BYTEBLOCK DROP CONSTRAINT FK_BYTEBLOCK_FILE; -- (optional)
      ALTER TABLE JBPM_COMMENT DROP CONSTRAINT FK_COMMENT_TOKEN; -- (optional)
      ALTER TABLE JBPM_COMMENT DROP CONSTRAINT FK_COMMENT_TSK; -- (optional)
      ALTER TABLE JBPM_DECISIONCONDITIONS DROP CONSTRAINT FK_DECCOND_DEC; -- (optional)
      ALTER TABLE JBPM_DELEGATION DROP CONSTRAINT FK_DELEGATION_PRCD; -- (optional)
      ALTER TABLE JBPM_EVENT DROP CONSTRAINT FK_EVENT_NODE; -- (optional)
      ALTER TABLE JBPM_EVENT DROP CONSTRAINT FK_EVENT_PROCDEF; -- (optional)
      ALTER TABLE JBPM_EVENT DROP CONSTRAINT FK_EVENT_TASK; -- (optional)
      ALTER TABLE JBPM_EVENT DROP CONSTRAINT FK_EVENT_TRANS; -- (optional)
      ALTER TABLE JBPM_JOB DROP CONSTRAINT FK_JOB_ACTION; -- (optional)
      ALTER TABLE JBPM_JOB DROP CONSTRAINT FK_JOB_NODE; -- (optional)
      ALTER TABLE JBPM_JOB DROP CONSTRAINT FK_JOB_PRINST; -- (optional)
      ALTER TABLE JBPM_JOB DROP CONSTRAINT FK_JOB_TOKEN; -- (optional)
      ALTER TABLE JBPM_JOB DROP CONSTRAINT FK_JOB_TSKINST; -- (optional)
      ALTER TABLE JBPM_LOG DROP CONSTRAINT FK_LOG_ACTION; -- (optional)
      ALTER TABLE JBPM_LOG DROP CONSTRAINT FK_LOG_CHILDTOKEN; -- (optional)
      ALTER TABLE JBPM_LOG DROP CONSTRAINT FK_LOG_DESTNODE; -- (optional)
      ALTER TABLE JBPM_LOG DROP CONSTRAINT FK_LOG_NEWBYTES; -- (optional)
      ALTER TABLE JBPM_LOG DROP CONSTRAINT FK_LOG_NODE; -- (optional)
      ALTER TABLE JBPM_LOG DROP CONSTRAINT FK_LOG_OLDBYTES; -- (optional)
      ALTER TABLE JBPM_LOG DROP CONSTRAINT FK_LOG_PARENT; -- (optional)
      ALTER TABLE JBPM_LOG DROP CONSTRAINT FK_LOG_TASKINST; -- (optional)
      ALTER TABLE JBPM_LOG DROP CONSTRAINT FK_LOG_TOKEN; -- (optional)
      ALTER TABLE JBPM_LOG DROP CONSTRAINT FK_LOG_TRANSITION; -- (optional)
      ALTER TABLE JBPM_LOG DROP CONSTRAINT FK_LOG_SOURCENODE; -- (optional)
      ALTER TABLE JBPM_LOG DROP CONSTRAINT FK_LOG_SWIMINST; -- (optional)
      ALTER TABLE JBPM_LOG DROP CONSTRAINT FK_LOG_VARINST; -- (optional)
      ALTER TABLE JBPM_MODULEDEFINITION DROP CONSTRAINT FK_MODDEF_PROCDEF; -- (optional)
      ALTER TABLE JBPM_MODULEDEFINITION DROP CONSTRAINT FK_TSKDEF_START; -- (optional)
      ALTER TABLE JBPM_MODULEINSTANCE DROP CONSTRAINT FK_MODINST_PRCINST; -- (optional)
      ALTER TABLE JBPM_MODULEINSTANCE DROP CONSTRAINT FK_TASKMGTINST_TMD; -- (optional)
      ALTER TABLE JBPM_NODE DROP CONSTRAINT FK_NODE_ACTION; -- (optional)
      ALTER TABLE JBPM_NODE DROP CONSTRAINT FK_DECISION_DELEG; -- (optional)
      ALTER TABLE JBPM_NODE DROP CONSTRAINT FK_NODE_PROCDEF; -- (optional)
      ALTER TABLE JBPM_NODE DROP CONSTRAINT FK_NODE_SCRIPT; -- (optional)
      ALTER TABLE JBPM_NODE DROP CONSTRAINT FK_NODE_SUPERSTATE; -- (optional)
      ALTER TABLE JBPM_NODE DROP CONSTRAINT FK_PROCST_SBPRCDEF; -- (optional)
      ALTER TABLE JBPM_POOLEDACTOR DROP CONSTRAINT FK_POOLEDACTOR_SLI; -- (optional)
      ALTER TABLE JBPM_PROCESSDEFINITION DROP CONSTRAINT FK_PROCDEF_STRTSTA; -- (optional)
      ALTER TABLE JBPM_PROCESSINSTANCE DROP CONSTRAINT FK_PROCIN_PROCDEF; -- (optional)
      ALTER TABLE JBPM_PROCESSINSTANCE DROP CONSTRAINT FK_PROCIN_ROOTTKN; -- (optional)
      ALTER TABLE JBPM_PROCESSINSTANCE DROP CONSTRAINT FK_PROCIN_SPROCTKN; -- (optional)
      ALTER TABLE JBPM_RUNTIMEACTION DROP CONSTRAINT FK_RTACTN_ACTION; -- (optional)
      ALTER TABLE JBPM_RUNTIMEACTION DROP CONSTRAINT FK_RTACTN_PROCINST; -- (optional)
      ALTER TABLE JBPM_SWIMLANE DROP CONSTRAINT FK_SWL_ASSDEL; -- (optional)
      ALTER TABLE JBPM_SWIMLANE DROP CONSTRAINT FK_SWL_TSKMGMTDEF; -- (optional)
      ALTER TABLE JBPM_SWIMLANEINSTANCE DROP CONSTRAINT FK_SWIMLANEINST_SL; -- (optional)
      ALTER TABLE JBPM_SWIMLANEINSTANCE DROP CONSTRAINT FK_SWIMLANEINST_TM; -- (optional)
      ALTER TABLE JBPM_TASK DROP CONSTRAINT FK_TASK_ASSDEL; -- (optional)
      ALTER TABLE JBPM_TASK DROP CONSTRAINT FK_TASK_PROCDEF; -- (optional)
      ALTER TABLE JBPM_TASK DROP CONSTRAINT FK_TASK_TASKMGTDEF; -- (optional)
      ALTER TABLE JBPM_TASK DROP CONSTRAINT FK_TSK_TSKCTRL; -- (optional)
      ALTER TABLE JBPM_TASK DROP CONSTRAINT FK_TASK_TASKNODE; -- (optional)
      ALTER TABLE JBPM_TASK DROP CONSTRAINT FK_TASK_STARTST; -- (optional)
      ALTER TABLE JBPM_TASK DROP CONSTRAINT FK_TASK_SWIMLANE; -- (optional)
      ALTER TABLE JBPM_TASKACTORPOOL DROP CONSTRAINT FK_TSKACTPOL_PLACT; -- (optional)
      ALTER TABLE JBPM_TASKACTORPOOL DROP CONSTRAINT FK_TASKACTPL_TSKI; -- (optional)
      ALTER TABLE JBPM_TASKCONTROLLER DROP CONSTRAINT FK_TSKCTRL_DELEG; -- (optional)
      ALTER TABLE JBPM_TASKINSTANCE DROP CONSTRAINT FK_TSKINS_PRCINS; -- (optional)
      ALTER TABLE JBPM_TASKINSTANCE DROP CONSTRAINT FK_TASKINST_TASK; -- (optional)
      ALTER TABLE JBPM_TASKINSTANCE DROP CONSTRAINT FK_TASKINST_TMINST; -- (optional)
      ALTER TABLE JBPM_TASKINSTANCE DROP CONSTRAINT FK_TASKINST_SLINST; -- (optional)
      ALTER TABLE JBPM_TASKINSTANCE DROP CONSTRAINT FK_TASKINST_TOKEN; -- (optional)
      ALTER TABLE JBPM_TOKEN DROP CONSTRAINT FK_TOKEN_NODE; -- (optional)
      ALTER TABLE JBPM_TOKEN DROP CONSTRAINT FK_TOKEN_PARENT; -- (optional)
      ALTER TABLE JBPM_TOKEN DROP CONSTRAINT FK_TOKEN_PROCINST; -- (optional)
      ALTER TABLE JBPM_TOKEN DROP CONSTRAINT FK_TOKEN_SUBPI; -- (optional)
      ALTER TABLE JBPM_TOKENVARIABLEMAP DROP CONSTRAINT FK_TKVARMAP_CTXT; -- (optional)
      ALTER TABLE JBPM_TOKENVARIABLEMAP DROP CONSTRAINT FK_TKVARMAP_TOKEN; -- (optional)
      ALTER TABLE JBPM_TRANSITION DROP CONSTRAINT FK_TRANSITION_FROM; -- (optional)
      ALTER TABLE JBPM_TRANSITION DROP CONSTRAINT FK_TRANS_PROCDEF; -- (optional)
      ALTER TABLE JBPM_TRANSITION DROP CONSTRAINT FK_TRANSITION_TO; -- (optional)
      ALTER TABLE JBPM_VARIABLEACCESS DROP CONSTRAINT FK_VARACC_PROCST; -- (optional)
      ALTER TABLE JBPM_VARIABLEACCESS DROP CONSTRAINT FK_VARACC_TSKCTRL; -- (optional)
      ALTER TABLE JBPM_VARIABLEACCESS DROP CONSTRAINT FK_VARACC_SCRIPT; -- (optional)
      ALTER TABLE JBPM_VARIABLEINSTANCE DROP CONSTRAINT FK_BYTEINST_ARRAY; -- (optional)
      ALTER TABLE JBPM_VARIABLEINSTANCE DROP CONSTRAINT FK_VARINST_PRCINST; -- (optional)
      ALTER TABLE JBPM_VARIABLEINSTANCE DROP CONSTRAINT FK_VAR_TSKINST; -- (optional)
      ALTER TABLE JBPM_VARIABLEINSTANCE DROP CONSTRAINT FK_VARINST_TK; -- (optional)
      ALTER TABLE JBPM_VARIABLEINSTANCE DROP CONSTRAINT FK_VARINST_TKVARMP; -- (optional)


      -- Drop all tables

      DROP TABLE JBPM_ACTION; -- (optional)
      DROP TABLE JBPM_BYTEARRAY; -- (optional)
      DROP TABLE JBPM_BYTEBLOCK; -- (optional)
      DROP TABLE JBPM_COMMENT; -- (optional)
      DROP TABLE JBPM_DECISIONCONDITIONS; -- (optional)
      DROP TABLE JBPM_DELEGATION; -- (optional)
      DROP TABLE JBPM_EVENT; -- (optional)
      DROP TABLE JBPM_EXCEPTIONHANDLER; -- (optional)
      DROP TABLE JBPM_JOB; -- (optional)
      DROP TABLE JBPM_LOG; -- (optional)
      DROP TABLE JBPM_MODULEDEFINITION; -- (optional)
      DROP TABLE JBPM_MODULEINSTANCE; -- (optional)
      DROP TABLE JBPM_NODE; -- (optional)
      DROP TABLE JBPM_POOLEDACTOR; -- (optional)
      DROP TABLE JBPM_PROCESSDEFINITION; -- (optional)
      DROP TABLE JBPM_PROCESSINSTANCE; -- (optional)
      DROP TABLE JBPM_RUNTIMEACTION; -- (optional)
      DROP TABLE JBPM_SWIMLANE; -- (optional)
      DROP TABLE JBPM_SWIMLANEINSTANCE; -- (optional)
      DROP TABLE JBPM_TASK; -- (optional)
      DROP TABLE JBPM_TASKACTORPOOL; -- (optional)
      DROP TABLE JBPM_TASKCONTROLLER; -- (optional)
      DROP TABLE JBPM_TASKINSTANCE; -- (optional)
      DROP TABLE JBPM_TOKEN; -- (optional)
      DROP TABLE JBPM_TOKENVARIABLEMAP; -- (optional)
      DROP TABLE JBPM_TRANSITION; -- (optional)
      DROP TABLE JBPM_VARIABLEACCESS; -- (optional)
      DROP TABLE JBPM_VARIABLEINSTANCE; -- (optional)


      --
      -- Record script finish
      --
      INSERT INTO alf_applied_patch
        (id, description, fixes_from_schema, fixes_to_schema, applied_to_schema, target_schema, applied_on_date, applied_to_server, was_executed, succeeded, report)
        VALUES
        (
          'patch.db-V5.2-remove-jbpm-tables-from-db', 'Removes all JBPM related tables from the database.',
          0, 10051, -1, 10052, now(), 'UNKNOWN', TRUE, TRUE, 'Script completed'
        );
      COMMIT;

      -- patch.db-V6.3-add-indexes-node-transaction
      -- Use CONCURRENTLY to avoid locking the tables for writes as that enable minimal downtime
      CREATE INDEX CONCURRENTLY idx_alf_node_ver ON alf_node (version);
      CREATE INDEX CONCURRENTLY idx_alf_node_txn ON alf_node (transaction_id);
      CREATE INDEX CONCURRENTLY idx_alf_txn_ctms_sc ON alf_transaction (commit_time_ms);
      CREATE INDEX CONCURRENTLY idx_alf_txn_id_ctms ON alf_transaction (id, commit_time_ms);

      --
      -- Record script finish
      --
      INSERT INTO alf_applied_patch
        (id, description, fixes_from_schema, fixes_to_schema, applied_to_schema, target_schema, applied_on_date, applied_to_server, was_executed, succeeded, report)
        VALUES
        (
          'patch.db-V6.3-add-indexes-node-transaction', 'Create aditional indexes on alf_node and alf_transaction',
          0, 14001, -1, 14002, now(), 'UNKNOWN', TRUE, TRUE, 'Script completed'
        );
      COMMIT;

      -- patch.db-V7.1.0-remove-alf_server-table
      ALTER TABLE alf_transaction
      DROP CONSTRAINT IF EXISTS fk_alf_txn_svr,
      DROP COLUMN IF EXISTS server_id;

      DROP TABLE IF EXISTS alf_server;
      DROP SEQUENCE IF EXISTS alf_server_seq;

      --
      -- Record script finish
      --
      INSERT INTO alf_applied_patch
        (id, description, fixes_from_schema, fixes_to_schema, applied_to_schema, target_schema, applied_on_date, applied_to_server, was_executed, succeeded, report)
        VALUES
        (
          'patch.db-V7.1.0-remove-alf_server-table', 'Removes alf_server table and constraints',
          0, 15000, -1, 15001, now(), 'UNKNOWN', TRUE, TRUE, 'alf_server table and constraints removed'
        );
      COMMIT;
    EOF

    echo "Executing patches SQL script …"
    psql --host="$DST_DB_HOST" --username="$DST_DB_USER" --dbname="$DST_DB_NAME" -f /tmp/alf-patches.sql -a

    rm -rv /home/job/db-dump ~/.pgpass 2>/dev/null || true

    if [ -n "$SLACK_WEBHOOK_URL" ]; then
      JSON_PAYLOAD=$(jq -n --arg text "Alfresco Migrate DB (${DST_ENV}) post-migration steps completed." '{text: $text}')
      curl -X POST -H 'Content-type: application/json' --data "$JSON_PAYLOAD" $SLACK_WEBHOOK_URL
    fi

    echo "Migration complete, sleeping to allow for review of log before pod termination …"
    sleep 3600

---
apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-db
  labels:
    name-prefix: migrate-db
spec:
  template:
    spec:
      containers:
        - name: migrate-db
          image: ghcr.io/ministryofjustice/hmpps-delius-alfresco-db-utils:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 4
              memory: 4Gi
          command:
            - /bin/entrypoint.sh
          env:
            - name: SRC_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: legacy-rds-instance
                  key: DATABASE_NAME
            - name: SRC_DB_USER
              valueFrom:
                secretKeyRef:
                  name: legacy-rds-instance
                  key: DATABASE_USERNAME
            - name: SRC_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: legacy-rds-instance
                  key: DATABASE_PASSWORD
            - name: SRC_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: legacy-rds-instance
                  key: RDS_INSTANCE_ADDRESS
            - name: DST_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: rds-instance-output
                  key: DATABASE_NAME
            - name: DST_DB_USER
              valueFrom:
                secretKeyRef:
                  name: rds-instance-output
                  key: DATABASE_USERNAME
            - name: DST_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: rds-instance-output
                  key: DATABASE_PASSWORD
            - name: DST_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: rds-instance-output
                  key: RDS_INSTANCE_ADDRESS
            - name: SLACK_WEBHOOK_URL
              value: "{{ .Values.slackWebhookUrl }}"
            - name: DST_ENV
              value: "{{ .Values.environment }}"
          volumeMounts:
            - name: migrate-db-script
              mountPath: /bin/entrypoint.sh
              readOnly: true
              subPath: entrypoint.sh
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 999
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
      serviceAccount: hmpps-migration-{{ .Values.environment }}
      serviceAccountName: hmpps-migration-{{ .Values.environment }}
      restartPolicy: Never
      volumes:
        - name: migrate-db-script
          configMap:
            name: migrate-db-script
            defaultMode: 0755
  backoffLimit: 0
