apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: delius-alfresco-cs-share
  annotations:
    external-dns.alpha.kubernetes.io/aws-weight: "100"
    kubernetes.io/ingress.class: default
spec:
  ingressClassName: default
