apiVersion: apps/v1
kind: Deployment
metadata:
  name: alfresco-content-services-alfresco-filestore
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0          # No new pods are created above the desired replica count
      maxUnavailable: 1    # Allow the old pod to be terminated before the new one starts
  template:
    spec:
      containers:
        - name: alfresco-content-services
          env:
            - name: scheduler.content.age.millis
              value: "518400000" # 6 days
            - name: scheduler.cleanup.interval
              value: "259200000" # 3 days

