apiVersion: apps/v1
kind: Deployment
metadata:
  name:  alfresco-content-services-transform-router
spec:
  template:
    spec:
      containers:
        - name: alfresco-transform-service
          env:
            - name: SPRING_ACTIVEMQ_POOL_ENABLED
              value: "true"
            - name: SPRING_ACTIVEMQ_POOL_MAXCONNECTIONS
              value: "100"
            - name: SPRING_ACTIVEMQ_POOL_IDLE_TIMEOUT
              value: "30000"          # 30 seconds idle timeout
            - name: SPRING_ACTIVEMQ_POOL_EXPIRY_TIMEOUT
              value: "60000"          # 60 seconds expiry timeout
            - name: FILE_STORE_URL
              valueFrom:
                configMapKeyRef:
                  name: alfresco-infrastructure
                  key: SFS_URL_API
