apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: alfresco-search-enterprise-mediation
spec:
  serviceName: alfresco-search-enterprise-mediation
  template:
    spec:
      containers:
        - name: alfresco-search-enterprise-mediation
          env:
            - name: SPRING_ACTIVEMQ_POOL_ENABLED
              value: "true"
            - name: SPRING_ACTIVEMQ_POOL_MAXCONNECTIONS
              value: "100"
            - name: SPRING_ACTIVEMQ_POOL_IDLE_TIMEOUT
              value: "30000"          # 30 seconds idle timeout
            - name: SPRING_ACTIVEMQ_POOL_EXPIRY_TIMEOUT
              value: "60000"          # 60 seconds expiry timeout
            - name: JAVA_OPTS
              value: "-Dspring.activemq.packages.trustAll=true"
            - name: ALFRESCO_SHAREDFILESTORE_BASEURL
              valueFrom:
                configMapKeyRef:
                  name: alfresco-infrastructure
                  key: SFS_URL_API
            - name: ALFRESCO_CONTENT_EVENT_RETRY_MAXALLOWED
              value: "10"
            - name: ALFRESCO_CONTENT_EVENT_RETRY_DELAY
              value: "1000"          # 1s initial
            - name: ALFRESCO_CONTENT_EVENT_RETRY_BACKOFF
              value: "2.0"           # exponential
            - name: ALFRESCO_CONTENT_EVENT_RETRY_MAXDELAY
              value: "60000"         # cap at 60s

