apiVersion: apps/v1
kind: Deployment
metadata:
  name: alfresco-content-services-alfresco-search-enterprise-path
spec:
  template:
    spec:
      containers:
        - name: alfresco-search-enterprise-path
          env:
            # - name: SPRING_ACTIVEMQ_POOL_ENABLED
            #   value: "true"
            # - name: SPRING_ACTIVEMQ_POOL_MAXCONNECTIONS
            #   value: "100"
            - name: JAVA_OPTS
              value: "-Dspring.activemq.packages.trustAll=true"
