apiVersion: apps/v1
kind: Deployment
metadata:
  name: alfresco-content-services-alfresco-filestore
spec:
  strategy:
    type: Recreate
    rollingUpdate: null
  template:
    spec:
      containers:
        - name: alfresco-content-services
          env:
            - name: scheduler.content.age.millis
              value: "518400000" # 3 days
            - name: scheduler.cleanup.interval
              value: "259200000" # 1 days
