apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: alfresco-search-enterprise-mediation
spec:
  serviceName: alfresco-search-enterprise-mediation
  selector:
    matchLabels:
      app: alfresco-search-enterprise-mediation
  strategy:
    type: Recreate
  template:
    spec:
      containers:
        - name: alfresco-search-enterprise-mediation
          env:
            - name: SPRING_ACTIVEMQ_POOL_ENABLED
              value: "true"
            - name: SPRING_ACTIVEMQ_POOL_MAX_CONNECTIONS
              value: "100"
            - name: SPRING_ACTIVEMQ_POOL_IDLE_TIMEOUT
              value: "30000"          # 30 seconds idle timeout
            - name: SPRING_ACTIVEMQ_POOL_EXPIRY_TIMEOUT
              value: "60000"          # 60 seconds expiry timeout
            - name: JAVA_OPTS
              value: "-Dspring.activemq.packages.trustAll=true"
            # - name: INPUT_ALFRESCO_MEDIATION_BATCH_EVENT_CHANNEL
            #   value: sjms-batch:mediation.event?completionTimeout=1000&completionSize=10&aggregationStrategy=#eventAggregator&consumerCount=20
