alfresco-transform-service:
  transformrouter:
    image:
      repository: quay.io/alfresco/alfresco-transform-router
      tag: 2.1.1
  pdfrenderer:
    image:
      tag: 3.1.1
  imagemagick:
    image:
      tag: 3.1.1
  libreoffice:
    image:
      tag: 3.1.1
  tika:
    image:
      tag: 3.1.1
  transformmisc:
    image:
      tag: 3.1.1
  filestore:
    image:
      tag: 2.1.1
alfresco-search:
  searchServicesImage:
    tag: 2.0.5.2
  insightEngineImage:
    tag: 2.0.5.2
alfresco-search-enterprise:
  liveIndexing:
    mediation:
      image:
        tag: 3.2.0.2
    content:
      image:
        tag: 3.2.0.2
    metadata:
      image:
        tag: 3.2.0.2
    path:
      image:
        tag: 3.2.0.2
  reindexing:
    image:
      tag: 3.2.0.2
alfresco-digital-workspace:
  image:
    tag: 3.1.1
alfresco-control-center:
  image:
    tag: 7.9.0
postgresql:
  image:
    tag: 14.4.0
postgresql-syncservice:
  image:
    tag: 14.4.0
alfresco-sync-service:
  image:
    tag: 3.11.1
alfresco-connector-ms365:
  image:
    tag: 1.1.3.2
alfresco-connector-msteams:
  image:
    tag: 1.1.0
