apiVersion: apps/v1
kind: Deployment
metadata:
  name: alfresco-content-services-transform-misc
spec:
  template:
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault