apiVersion: apps/v1
kind: Deployment
metadata:
  name: alfresco-content-services-alfresco-search-enterprise-path
spec:
  template:
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault