alfresco-repository:
  replicaCount: 10
  image:
    repository: 754256621582.dkr.ecr.eu-west-2.amazonaws.com/hmpps-migration/alfresco-content-repository
    tag: release_7.3.2_elasticsearch-r5.0.2-content-latest
  resources: # requests and limits set closer together to ensure CP stability
    requests:
      cpu: 1
      memory: 6Gi
    limits:
      cpu: 4
      memory: 10Gi
share:
  replicaCount: 1
  image:
    repository: 754256621582.dkr.ecr.eu-west-2.amazonaws.com/hmpps-migration/alfresco-share
    tag: release_7.3.2_elasticsearch-r5.0.2-chart-7.0.3-share-latest
externalProtocol: https
externalPort: 443
alfresco-search-enterprise:
  liveIndexing:
    # set in value-versions yaml
    content:
      replicaCount: 4
    metadata:
      replicaCount: 2
    mediation:
      replicaCount: 2
alfresco-transform-service:
  tika:
    replicaCount: 8
    resources:
      requests:
        cpu: "0.5"
        memory: "2048Mi"
      limits:
        cpu: "2"
        memory: 6Gi
  transformrouter:
    replicaCount: 8
    resources:
      requests:
        cpu: "0.75"
        memory: "512Mi"
      limits:
        cpu: "2"
        memory: 2Gi
global:
  known_urls:
    - https://hmpps-delius-alfresco-stage.apps.live.cloud-platform.service.justice.gov.uk
    - https://share.hmpps-delius-alfresco-stage.apps.live.cloud-platform.service.justice.gov.uk
    - https://alf-sfs.stage.delius-core.hmpps-preproduction.modernisation-platform.service.justice.gov.uk
