---
name: Alfresco Data Refresh

on:
  workflow_dispatch:
    inputs:
      source_env:
        description: Environment to copy data from
        required: true
        type: choice
        options:
          - dev
      destination_env:
        description: Environment to copy data to
        required: true
        type: choice
        options:
          - poc

permissions:
  contents: read

jobs:
  stop-destination-environment:
    name: Stop ${{ github.event.inputs.destination_env }} Environment
    runs-on: ubuntu-22.04
    environment:
      name: ${{ github.event.inputs.destination_env }}
    steps:
    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Validate environments
      run: |
        echo "Source: ${{ github.event.inputs.source_env }}"
        echo "Destination: ${{ github.event.inputs.destination_env }}"

        if [ "${{ github.event.inputs.source_env }}" = "${{ github.event.inputs.destination_env }}" ]; then
          echo "ERROR: Source and destination environments cannot be the same."
          exit 1
        fi

    - name: Configure kubectl
      run: |
        echo "${{ secrets.KUBE_CERT }}" > ca.crt
        kubectl config set-cluster ${KUBE_CLUSTER} --certificate-authority=./ca.crt --server=https://${KUBE_CLUSTER}
        kubectl config set-credentials deploy-user --token=${{ secrets.KUBE_TOKEN }}
        kubectl config set-context ${KUBE_CLUSTER} --cluster=${KUBE_CLUSTER} --user=deploy-user --namespace=${KUBE_NAMESPACE}
        kubectl config use-context ${KUBE_CLUSTER}
      env:
        KUBE_NAMESPACE: ${{ secrets.KUBE_NAMESPACE }}
        KUBE_CLUSTER: ${{ secrets.KUBE_CLUSTER }}

    - name: Install Task
      uses: go-task/setup-task@3be4020d41929789a01026e0e427a4321ce0ad44 # v2.0.0
      with:
        version: 'v3.49.1'

    - name: Stop ${{ github.event.inputs.destination_env }} Environment
      run: task scale_down_deployments ENV=${{ github.event.inputs.destination_env }}

  refresh-db:
    name: Refresh DB
    runs-on: ubuntu-22.04
    # environment:
    #   name: ${{ github.event.inputs.source_env }}
    # needs: stop-destination-environment
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install kubectl
        uses: azure/setup-kubectl@776406bce94f63e41d621b960d78ee25c8b76ede # v4.0.1
        with:
          version: 'v1.33.5'
        id: kubectl_install

      - uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4.3.1
        with:
          version: 'v3.15.2'
        id: install

      - name: Configure kubectl
        run: |
          echo "${{ secrets.KUBE_CERT }}" > ca.crt
          kubectl config set-cluster ${KUBE_CLUSTER} --certificate-authority=./ca.crt --server=https://${KUBE_CLUSTER}
          kubectl config set-credentials deploy-user --token=${{ secrets.KUBE_TOKEN }}
          kubectl config set-context ${KUBE_CLUSTER} --cluster=${KUBE_CLUSTER} --user=deploy-user --namespace=${KUBE_NAMESPACE}
          kubectl config use-context ${KUBE_CLUSTER}
        env:
          KUBE_NAMESPACE: ${{ secrets.KUBE_NAMESPACE }}
          KUBE_CLUSTER: ${{ secrets.KUBE_CLUSTER }}

      - name: Uninstall DB Refresh chart
        run: helm uninstall refresh-db --ignore-not-found

      - name: Fetch Source Env RDS Details
        working-directory: jobs/refresh-db
        run: |
          echo "Database refresh..."
          # helm install refresh-db . \
          #   --set sourceEnvironment=${{ github.event.inputs.source_env }} \
          #   --set destinationEnvironment=${{ github.event.inputs.destination_env }} \
          #   --set slackWebhookUrl=${{ secrets.SLACK_WEBHOOK_URL }}
      - name: DB Refresh
        working-directory: jobs/refresh-db
        run: |
          echo "Database refresh..."
          # helm install refresh-db . \
          #   --set sourceEnvironment=${{ github.event.inputs.source_env }} \
          #   --set destinationEnvironment=${{ github.event.inputs.destination_env }} \
          #   --set slackWebhookUrl=${{ secrets.SLACK_WEBHOOK_URL }}

  refresh-s3:
    name: Refresh S3
    runs-on: ubuntu-22.04
    environment:
      name: ${{ github.event.inputs.source_env }}
    needs: stop-destination-environment
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install kubectl
        uses: azure/setup-kubectl@776406bce94f63e41d621b960d78ee25c8b76ede # v4.0.1
        with:
          version: 'v1.33.5'
        id: kubectl_install

      - uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4.3.1
        with:
          version: 'v3.15.2'
        id: install

      - name: Configure kubectl
        run: |
          echo "${{ secrets.KUBE_CERT }}" > ca.crt
          kubectl config set-cluster ${KUBE_CLUSTER} --certificate-authority=./ca.crt --server=https://${KUBE_CLUSTER}
          kubectl config set-credentials deploy-user --token=${{ secrets.KUBE_TOKEN }}
          kubectl config set-context ${KUBE_CLUSTER} --cluster=${KUBE_CLUSTER} --user=deploy-user --namespace=${KUBE_NAMESPACE}
          kubectl config use-context ${KUBE_CLUSTER}
        env:
          KUBE_NAMESPACE: ${{ secrets.KUBE_NAMESPACE }}
          KUBE_CLUSTER: ${{ secrets.KUBE_CLUSTER }}
      
      - name: Uninstall S3 Refresh chart
        run: helm uninstall refresh-s3 --ignore-not-found

      - name: S3 Refresh
        working-directory: jobs/refresh-s3
        run: |
          echo "S3 refresh..."
          # set -xeo pipefail

          # SERVICE_POD_DEPLOYMENT=$(kubectl get deployment -l app=service-pod -o jsonpath="{.items[0].metadata.name}")
          # SERVICE_POD_NAME=$(kubectl get pod -l app=$SERVICE_POD_DEPLOYMENT -o jsonpath="{.items[0].metadata.name}")

          # SRC_BUCKET=$(kubectl get secrets s3-bucket-output -o jsonpath='{.data.BUCKET_NAME}' | base64 -d)

          # DIRS=$(kubectl exec $SERVICE_POD_NAME -- aws s3 ls $SRC_BUCKET | grep -v contentstore | awk '/\/$/ && NF {print $2}' | tr -d '/' | tr '\n' ',' | sed 's/,$/\n/')

          # helm install refresh-s3 . \
          #   --set sourceEnvironment=${{ github.event.inputs.source_env }} \
          #   --set destinationEnvironment=${{ github.event.inputs.destination_env }} \
          #   --set directories="{${DIRS}}"

          # kubectl wait jobs -l name-prefix=refresh-s3 --for=condition=complete --timeout 10h

      - name: Uninstall S3 Refresh chart
        run: helm uninstall refresh-s3 --ignore-not-found

  start-destination-environment:
    name: Start ${{ github.event.inputs.destination_env }} Environment
    runs-on: ubuntu-22.04
    environment:
      name: ${{ github.event.inputs.destination_env }}
    needs:
      - refresh-db
      - refresh-s3

    steps:
    - name: Configure kubectl
      run: |
        echo "${{ secrets.KUBE_CERT }}" > ca.crt
        kubectl config set-cluster ${KUBE_CLUSTER} --certificate-authority=./ca.crt --server=https://${KUBE_CLUSTER}
        kubectl config set-credentials deploy-user --token=${{ secrets.KUBE_TOKEN }}
        kubectl config set-context ${KUBE_CLUSTER} --cluster=${KUBE_CLUSTER} --user=deploy-user --namespace=${KUBE_NAMESPACE}
        kubectl config use-context ${KUBE_CLUSTER}
      env:
        KUBE_NAMESPACE: ${{ secrets.KUBE_NAMESPACE }}
        KUBE_CLUSTER: ${{ secrets.KUBE_CLUSTER }}

    - name: Start ${{ github.event.inputs.destination_env }} Environment
      run: task scale_up_deployments ENV=${{ github.event.inputs.destination_env }}