name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
        env:
            GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Add helm dependencies
        run: |
          helm repo add alfresco-common https://alfresco.github.io/alfresco-helm-charts/
          helm repo add bitnami https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami/

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: alfresco-content-services/charts
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
