name: Alfresco Restore Docs Worker Process

on:
  push:
    branches:
      - "NIT-1120-alfresco-recover-deleted-documents"
  workflow_dispatch:
    inputs:
      which_env:
        description: Environment where this restore docs process will run
        required: true
        type: choice
        options:
          - poc

permissions:
  contents: read

jobs:
  restore-docs-worker:
    name: Restore Docs from Glacier 
    runs-on: ubuntu-22.04
    environment:
      name: ${{ github.event.inputs.which_env }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4.1.1

      - name: Configure kubectl
        run: |
          echo "${{ secrets.KUBE_CERT }}" > ca.crt
          kubectl config set-cluster ${KUBE_CLUSTER} --certificate-authority=./ca.crt --server=https://${KUBE_CLUSTER}
          kubectl config set-credentials deploy-user --token=${{ secrets.KUBE_TOKEN }}
          kubectl config set-context ${KUBE_CLUSTER} --cluster=${KUBE_CLUSTER} --user=deploy-user --namespace=${KUBE_NAMESPACE}
          kubectl config use-context ${KUBE_CLUSTER}
        env:
          KUBE_NAMESPACE: ${{ secrets.KUBE_NAMESPACE }}
          KUBE_CLUSTER: ${{ secrets.KUBE_CLUSTER }}
        
      - name: Create ConfigMap using the restore-docs-worker.sh script
        run: |
          kubectl create configmap restore-docs-worker-cm --from-file=scripts/restore-docs-worker.sh
    
      - name: Start Restore Docs Job
        run: |
          kubectl apply -f jobs/restore-docs-worker.yaml
          kubectl wait --timeout 10m --for=condition=complete job/restore-docs-worker

      - name: Delete Restore Docs Job
        run: kubectl delete job restore-docs-worker
      
      - name: Delete configmap
        run: kubectl delete cm restore-docs-worker-cm