name: Scale Up Lower Environments

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to scale up"
        required: true
        type: choice
        options:
          - poc
          - dev
          - test
          - stage
          - training
          - preprod

  workflow_call:
    inputs:
      environment:
        description: 'Environment to scale up'
        required: true
        type: string
  
jobs:
  scale-up:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    
      - name: Install Kubernetes
        uses: azure/setup-kubectl@c0c8b32d33a5244f1e5947304550403b63930415 # v4.0.0
        with:
          version: 'v1.26.0' # default is latest stable
        id: kubectl_install
      
      - name: Install yq
        uses: dcarbone/install-yq-action@64b1b9eb28920bb1a4c13c05321df284f9a8f940 # v1.1.1
        with:
          download-compressed: true
          version: "v4.35.1"
          force: true

      - name: Scaling up Deployments in ${{ inputs.environment }} namespace
        env:
          KUBE_NAMESPACE: ${{ secrets.KUBE_NAMESPACE }}
          KUBE_CLUSTER: ${{ secrets.KUBE_CLUSTER }}
        run: |          
          echo "${{ secrets.KUBE_CERT }}" > ca.crt
          kubectl config set-cluster ${KUBE_CLUSTER} --certificate-authority=./ca.crt --server=https://${KUBE_CLUSTER}
          kubectl config set-credentials deploy-user --token=${{ secrets.KUBE_TOKEN }}
          kubectl config set-context ${KUBE_CLUSTER} --cluster=${KUBE_CLUSTER} --user=deploy-user --namespace=${KUBE_NAMESPACE}
          kubectl config use-context ${KUBE_CLUSTER}

          kubectl config set-context --current --namespace=${KUBE_NAMESPACE}
         
      - name: Install Task
        uses: arduino/setup-task@24c5e13bce349197642746563945fcdf9355e8f4 # v2.0.0
        with:
          version: 3.x

      - name: Run Task
        run: task scale_up_deployments ENV=${{ inputs.environment }}