name: Scale Up Lower Environments

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to scale up"
        required: true
        type: choice
        options:
          - poc
          - dev
          - test
          - stage
          - preprod
          - prod

  workflow_call:
    inputs:
      environment:
        description: 'Environment to scale up'
        required: true
        type: string
  
jobs:
  scale-up:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
    
      - name: Install Kubernetes
        uses: azure/setup-kubectl@v3.2
        with:
          version: 'v1.26.0' # default is latest stable
        id: kubectl_install
      
      - name: Install yq
        uses: dcarbone/install-yq-action@v1.1.1
        with:
          download-compressed: true
          version: "v4.35.1"
          force: true

      - name: Scaling up Deployments in ${{ inputs.environment }} namespace
        env:
          KUBE_NAMESPACE: ${{ secrets.KUBE_NAMESPACE }}
          KUBE_CLUSTER: ${{ secrets.KUBE_CLUSTER }}
        run: |          
          echo "${{ secrets.KUBE_CERT }}" > ca.crt
          kubectl config set-cluster ${KUBE_CLUSTER} --certificate-authority=./ca.crt --server=https://${KUBE_CLUSTER}
          kubectl config set-credentials deploy-user --token=${{ secrets.KUBE_TOKEN }}
          kubectl config set-context ${KUBE_CLUSTER} --cluster=${KUBE_CLUSTER} --user=deploy-user --namespace=${KUBE_NAMESPACE}
          kubectl config use-context ${KUBE_CLUSTER}

          kubectl config set-context --current --namespace=${KUBE_NAMESPACE}
         
      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x

      - name: Run Task
        run: task scale_up_deployments ENV=${{ inputs.environment }}