name: Schedule Scale Up Environments

on:
  push:
    branches:
      - 'TM-1077*'
  workflow_dispatch:

jobs:
  schedule-scale-up:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: ["poc"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Determine Environment
        id: which-env
        run: |
          if [[ "0 6 * * 1-5" == "${{ github.event.schedule }}" && "${{ matrix.environment }}" == "poc" ]]; then
            echo "ENV_TO_SCALE=poc" >> $GITHUB_OUTPUT
          elif [[ "0 3 * * 1-5" == "${{ github.event.schedule }}" && "${{ matrix.environment }}" == "dev" ]]; then
            echo "ENV_TO_SCALE=dev" >> $GITHUB_OUTPUT
          else
            echo "ENV_TO_SCALE=poc" >> $GITHUB_OUTPUT
          fi
  
  call-scale-up:
    needs: schedule-scale-up
    if: needs.schedule-scale-up.outputs.ENV_TO_SCALE != 'NONE'
    uses: ./.github/workflows/scale-up.yaml
    with:
      environment: ${{ needs.schedule-scale-up.outputs.ENV_TO_SCALE }}-preapproved
