name: Schedule Scale Up Environments

on:
  push:
    branches:
      - 'TM-1077*'
  workflow_dispatch:

jobs:
  checkout-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

  schedule-scale-up:
    runs-on: ubuntu-latest
    needs: checkout-repo
    strategy:
      matrix:
        environment: ["poc"]
    outputs:
      env_to_scale: ${{ steps.which-env.outputs.result }}
    steps:
      - name: Determine Environment
        id: which-env
        run: |
            echo "result=poc" >> $GITHUB_OUTPUT
  
  use-env-to-scale:
    runs-on: ubuntu-latest
    needs: schedule-scale-up
    steps:
      - name: Debug env_to_scale
        run: echo "env_to_scale is ${{ needs.schedule-scale-up.outputs.env_to_scale }}"

  call-scale-up:
    needs: schedule-scale-up
    if: needs.schedule-scale-up.outputs.env_to_scale != 'NONE'
    uses: ./.github/workflows/scale-up.yaml
    with:
      environment: ${{ needs.schedule-scale-up.outputs.env_to_scale }}-preapproved