name: Scheduled Daily Rollout Restart

on:
  schedule:
    - cron: '0 3 * * *'  # 03:00 UTC daily
  workflow_dispatch:

jobs:
  daily-restart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Trigger rollout restart
        uses: ./.github/workflows/rollout-restart.yaml
        with:
          environment: preprod
          deployment: alfresco-content-services-alfresco-cs-repository