name: Scheduled Daily Rollout Restart

on:
  # No need to scheduled restarts at the moment. Should be expanded so that schedules per env can be defined.
  #schedule:
    #- cron: '0 5 * * *'  # 05:00 UTC daily
  workflow_dispatch:

jobs:
  daily-restart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Trigger rollout restart
        uses: ./.github/workflows/rollout-restart.yaml
        with:
          environment: preprod
          deployment: alfresco-content-services-alfresco-repository