name: "Alfresco: Unindexed Content Reindexing Schedule"
# This workflow triggers the reindexing of unindexed content on a schedule.
# It runs for the "preprod" and "prod" environments only.
on:
  schedule:
    # Run every hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  batch-reindex:
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        #environment: ["preprod", "prod"]
        environment: ["preprod"]
    uses: ./.github/workflows/unindexed-content-runner.yml
    with:
      environment: ${{matrix.environment}}
      # Look-back window in hours
      hours: "2"
    secrets: inherit