apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-restart-repository-pods
spec:
  schedule: "0 5 * * *"   # Every day at 5 AM UTC
  successfulJobsHistoryLimit: 1   # keep only the most recent successful Job
  failedJobsHistoryLimit: 1       # keep only the most recent failed Job
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 3600
      template:
        spec:
          serviceAccountName: hmpps-migration-prod    # must have RBAC to restart deployments
          restartPolicy: OnFailure
          containers:
          - name: restart-repo
            image: public.ecr.aws/bitnami/kubectl:latest
            imagePullPolicy: IfNotPresent
            command: ["/bin/sh","-c"]
            args:
            - |
              set -eu
              echo "Restarting deployment alfresco-content-services-alfresco-repository at $(date)"
              kubectl rollout restart deployment alfresco-content-services-alfresco-repository
            securityContext:
              allowPrivilegeEscalation: false
              runAsNonRoot: true
              seccompProfile:
                type: RuntimeDefault
              capabilities:
                drop:
                  - NET_RAW
                  - ALL
