apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  - alf-prop-config-map.yaml

patches:
  - path: patch-ingress-repository.yaml
  - path: patch-ingress-share.yaml
  - path: patch-infra-config-map.yaml
